image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
    - build
    - test

variables:
    test: "Example.Test"

before_script:
    - "cd src/Chip8"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"

test:
    stage: test
    script: 
        - "cd src/Chip8"
        - "dotnet test"
